---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-day2-worker1
  namespace: patch-me
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
data:
  username: QURNSU4=
  password: YWx0aW9zdGFyITIz
type: Opaque
