---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: rna4-nmstate
  namespace: rna4
  labels:
    cluster-name: rna4-nmstate
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "6"
spec:
  config:
    interfaces:
    dns-resolver:
      config:
        server:
          - 10.6.1.3
    routes:
      config:
  interfaces:
